const { categoryQueries, eventQueries } = require('./queries');

console.log('Seeding database with comprehensive sample data...');

try {
    // Comprehensive events data - 20 events per category
    const sampleEvents = [
        // Sports & Recreation (Category 1) - 20 events
        {
            title: 'Community Football League Registration',
            description: 'Registration opens for the autumn community football league',
            content: 'Join our inclusive football league for adults of all skill levels. Games are played on Saturday mornings with a focus on fun, fitness, and community spirit. Equipment provided, just bring enthusiasm!',
            image_url: '/images/football-league.jpg',
            location: 'Excel Centre Sports Field',
            date: '2025-10-05',
            start_time: '09:00',
            end_time: '12:00',
            address: '1 Western Gateway, Royal Victoria Dock, London E16 1XL',
            category_id: 1
        },
        {
            title: 'Morning Yoga Classes',
            description: 'Start your day with gentle yoga sessions for all levels',
            content: 'Begin each morning with energising yoga sessions designed for all fitness levels. Our certified instructors will guide you through poses that improve flexibility, strength, and mindfulness.',
            image_url: '/images/yoga-class.jpg',
            location: 'Community Centre',
            date: '2025-10-08',
            start_time: '07:00',
            end_time: '08:00',
            address: '45 Stratford High Street, Stratford, London E15 2QF',
            category_id: 1
        },
        {
            title: 'Tennis Tournament Championship',
            description: 'Annual community tennis tournament for all ages',
            content: 'Our biggest tennis event of the year! Categories for juniors, adults, and seniors. Prizes for winners and participation medals for all. Light refreshments provided throughout the day.',
            image_url: '/images/tennis-tournament.jpg',
            location: 'Stratford Tennis Courts',
            date: '2025-10-12',
            start_time: '08:00',
            end_time: '17:00',
            address: 'The Westfield Shopping Centre, Montfichet Road, London E20 1EJ',
            category_id: 1
        },
        {
            title: 'Swimming Lessons for Beginners',
            description: 'Learn to swim in a safe and supportive environment',
            content: 'Professional swimming instructors will teach basic water safety and swimming techniques. Classes are small to ensure personalised attention. All equipment provided.',
            image_url: '/images/swimming-lessons.jpg',
            location: 'Stratford Park Pool',
            date: '2025-10-15',
            start_time: '10:00',
            end_time: '11:30',
            address: '154 Burford Road, Stratford, London E15 2SP',
            category_id: 1
        },
        {
            title: 'Cycling Group Weekend Ride',
            description: 'Join our weekly community cycling group for scenic rides',
            content: 'Explore local paths and roads with fellow cycling enthusiasts. Routes suitable for intermediate riders. Helmets required, bikes available for hire at discounted rates.',
            image_url: '/images/cycling-group.jpg',
            location: 'Queen Elizabeth Olympic Park',
            date: '2025-10-19',
            start_time: '08:30',
            end_time: '11:00',
            address: 'Queen Elizabeth Olympic Park, Stratford, London E20 2ST',
            category_id: 1
        },
        {
            title: 'Basketball Skills Clinic',
            description: 'Improve your basketball fundamentals with experienced coaches',
            content: 'Work on shooting, dribbling, and defensive skills with local basketball coaches. Suitable for ages 12 and up. Basketballs provided, just bring sports kit and water.',
            image_url: '/images/basketball-clinic.jpg',
            location: 'Excel Centre Indoor Court',
            date: '2025-10-22',
            start_time: '14:00',
            end_time: '16:00',
            address: '1 Western Gateway, Royal Victoria Dock, London E16 1XL',
            category_id: 1
        },
        {
            title: 'Senior Fitness Walking Group',
            description: 'Low-impact walking group designed for active seniors',
            content: 'Join other active seniors for pleasant walks through our community. Routes are flat and well-maintained. Social coffee hour follows each walk session.',
            image_url: '/images/senior-walking.jpg',
            location: 'Community Center',
            date: '2025-10-25',
            start_time: '09:00',
            end_time: '10:30',
            address: '789 Community Way, Main Entrance',
            category_id: 1
        },
        {
            title: 'Youth Martial Arts Workshop',
            description: 'Introduction to martial arts for children and teens',
            content: 'Learn basic martial arts techniques focusing on discipline, respect, and self-defense. Experienced instructors ensure a safe learning environment for all participants.',
            image_url: '/images/martial-arts.jpg',
            location: 'Community Center Gym',
            date: '2025-10-28',
            start_time: '15:30',
            end_time: '17:00',
            address: '789 Community Way, Main Gymnasium',
            category_id: 1
        },
        {
            title: 'Softball League Season Opener',
            description: 'Kick off the community softball season with opening day festivities',
            content: 'Season opener includes team introductions, ceremonial first pitch, and games throughout the day. Family-friendly event with food vendors and activities for children.',
            image_url: '/images/softball-opener.jpg',
            location: 'Stratford Sports Fields',
            date: '2025-11-02',
            start_time: '10:00',
            end_time: '16:00',
            address: 'Stratford Shopping Centre, Athletic Complex',
            category_id: 1
        },
        {
            title: 'Badminton Club Weekly Session',
            description: 'Regular badminton games for players of all skill levels',
            content: 'Friendly competitive and recreational badminton games. Equipment available for borrowing. Great way to meet new people while staying active.',
            image_url: '/images/badminton-club.jpg',
            location: 'Excel Centre Indoor Hall',
            date: '2025-11-05',
            start_time: '19:00',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Multi-Purpose Hall',
            category_id: 1
        },
        {
            title: 'Family Fun Run 5K',
            description: 'Non-competitive 5K fun run for the whole family',
            content: 'A community fun run celebrating fitness and family time. Strollers welcome, walking encouraged. Finish line festival with healthy snacks and entertainment.',
            image_url: '/images/family-fun-run.jpg',
            location: 'Central Park',
            date: '2025-11-09',
            start_time: '08:00',
            end_time: '11:00',
            address: 'Central Park Main Entrance, Running Trail Start',
            category_id: 1
        },
        {
            title: 'Aqua Aerobics Classes',
            description: 'Low-impact water exercise classes for all fitness levels',
            content: 'Gentle water-based exercises that are easy on joints while providing excellent cardiovascular benefits. Particularly beneficial for seniors and those with mobility issues.',
            image_url: '/images/aqua-aerobics.jpg',
            location: 'Community Pool',
            date: '2025-11-12',
            start_time: '10:00',
            end_time: '11:00',
            address: '456 Aquatic Drive, Community Pool',
            category_id: 1
        },
        {
            title: 'Golf Putting Competition',
            description: 'Mini golf tournament at our community putting green',
            content: 'Fun putting competition with prizes for various age categories. Entry fee includes equipment rental and refreshments. Suitable for all ages and skill levels.',
            image_url: '/images/putting-competition.jpg',
            location: 'Stratford Recreation Area',
            date: '2025-11-16',
            start_time: '13:00',
            end_time: '16:00',
            address: 'Stratford Shopping Centre, Mini Golf Course',
            category_id: 1
        },
        {
            title: 'Dance Fitness Workshop',
            description: 'High-energy dance workout combining fun and fitness',
            content: 'Learn easy dance moves while getting a great workout. No dance experience necessary - just bring comfortable shoes and a positive attitude. All music genres included.',
            image_url: '/images/dance-fitness.jpg',
            location: 'Community Center Studio',
            date: '2025-11-19',
            start_time: '18:00',
            end_time: '19:30',
            address: '789 Community Way, Dance Studio',
            category_id: 1
        },
        {
            title: 'Table Tennis Tournament',
            description: 'Competitive table tennis tournament with multiple divisions',
            content: 'Tournament brackets for beginners, intermediate, and advanced players. Single and doubles competitions available. Equipment provided, registration required.',
            image_url: '/images/table-tennis.jpg',
            location: 'Excel Centre Game Room',
            date: '2025-11-23',
            start_time: '12:00',
            end_time: '17:00',
            address: '100 Excel Centre Drive, Recreation Room',
            category_id: 1
        },
        {
            title: 'Outdoor Boot Camp Challenge',
            description: 'High-intensity outdoor fitness training session',
            content: 'Push your limits with this challenging outdoor workout featuring cardio, strength training, and team challenges. Modifications available for all fitness levels.',
            image_url: '/images/boot-camp.jpg',
            location: 'Central Park Training Area',
            date: '2025-11-26',
            start_time: '07:00',
            end_time: '08:00',
            address: 'Central Park, Fitness Equipment Area',
            category_id: 1
        },
        {
            title: 'Rock Climbing Introduction',
            description: 'Learn basic rock climbing techniques with certified instructors',
            content: 'Indoor rock climbing session for beginners. All safety equipment provided and proper instruction given. Great introduction to this exciting sport.',
            image_url: '/images/rock-climbing.jpg',
            location: 'Adventure Sports Center',
            date: '2025-11-30',
            start_time: '15:00',
            end_time: '17:00',
            address: '321 Adventure Way, Climbing Wall Facility',
            category_id: 1
        },
        {
            title: 'Volleyball League Playoffs',
            description: 'Championship games for community volleyball league',
            content: 'Exciting playoff matches determining this seasons volleyball champions. Spectators welcome to cheer on their favorite teams. Awards ceremony follows final match.',
            image_url: '/images/volleyball-playoffs.jpg',
            location: 'Excel Centre Volleyball Courts',
            date: '2025-12-03',
            start_time: '18:00',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Volleyball Complex',
            category_id: 1
        },
        {
            title: 'Pilates Workshop',
            description: 'Learn proper Pilates form and techniques',
            content: 'Focus on core strength, flexibility, and body alignment through controlled movements. Suitable for beginners, mats and equipment provided.',
            image_url: '/images/pilates-workshop.jpg',
            location: 'Community Center Wellness Room',
            date: '2025-12-07',
            start_time: '11:00',
            end_time: '12:30',
            address: '789 Community Way, Wellness Center',
            category_id: 1
        },
        {
            title: 'Winter Sports Preparation Clinic',
            description: 'Get ready for winter sports season with conditioning and technique tips',
            content: 'Prepare for winter activities with specific conditioning exercises and technique workshops. Covers skiing, ice skating, and winter hiking preparation.',
            image_url: '/images/winter-sports.jpg',
            location: 'Excel Centre Training Room',
            date: '2025-12-10',
            start_time: '16:00',
            end_time: '18:00',
            address: '100 Excel Centre Drive, Training Facility',
            category_id: 1
        },

        // Health & Wellness (Category 2) - 20 events
        {
            title: 'Monthly Health Screening Fair',
            description: 'Free health screenings and wellness consultations',
            content: 'Comprehensive health fair offering blood pressure checks, diabetes screening, BMI assessments, and consultations with healthcare professionals. All services are free and confidential.',
            image_url: '/images/health-screening.jpg',
            location: 'Community Center Main Hall',
            date: '2025-10-06',
            start_time: '09:00',
            end_time: '15:00',
            address: '789 Community Way, Main Hall',
            category_id: 2
        },
        {
            title: 'Mental Health Support Group',
            description: 'Safe space for discussing mental health challenges and solutions',
            content: 'Weekly support group meetings led by licensed counselors. Confidential environment for sharing experiences and coping strategies. All are welcome.',
            image_url: '/images/mental-health-support.jpg',
            location: 'Community Center Quiet Room',
            date: '2025-10-09',
            start_time: '18:30',
            end_time: '20:00',
            address: '789 Community Way, Room 105',
            category_id: 2
        },
        {
            title: 'Nutrition Workshop: Healthy Eating on a Budget',
            description: 'Learn how to eat well without breaking the bank',
            content: 'Practical nutrition workshop covering meal planning, budget shopping, and simple healthy recipes. Take-home materials and recipe cards included.',
            image_url: '/images/nutrition-workshop.jpg',
            location: 'Community Center Kitchen',
            date: '2025-10-13',
            start_time: '14:00',
            end_time: '16:00',
            address: '789 Community Way, Teaching Kitchen',
            category_id: 2
        },
        {
            title: 'Senior Health and Fitness Assessment',
            description: 'Comprehensive health evaluation for seniors 65+',
            content: 'Free health assessments including balance testing, strength evaluation, and mobility screening. Personalized fitness recommendations provided by certified professionals.',
            image_url: '/images/senior-health.jpg',
            location: 'Excel Centre Wellness Wing',
            date: '2025-10-16',
            start_time: '10:00',
            end_time: '14:00',
            address: '100 Excel Centre Drive, Health Assessment Center',
            category_id: 2
        },
        {
            title: 'Stress Management Workshop',
            description: 'Learn effective techniques for managing daily stress',
            content: 'Interactive workshop covering breathing exercises, mindfulness techniques, and practical stress reduction strategies. Take-home resources and ongoing support information provided.',
            image_url: '/images/stress-management.jpg',
            location: 'Community Center Meditation Room',
            date: '2025-10-20',
            start_time: '19:00',
            end_time: '21:00',
            address: '789 Community Way, Wellness Center',
            category_id: 2
        },
        {
            title: 'Flu Shot Clinic',
            description: 'Annual flu vaccinations available for all community members',
            content: 'Free flu vaccinations administered by registered nurses. No appointment necessary, just bring your health card. Information about other recommended vaccines also available.',
            image_url: '/images/flu-shot.jpg',
            location: 'Stratford Health Center',
            date: '2025-10-23',
            start_time: '12:00',
            end_time: '18:00',
            address: 'Stratford Shopping Centre, Medical Wing',
            category_id: 2
        },
        {
            title: 'Meditation and Mindfulness Session',
            description: 'Guided meditation for beginners and experienced practitioners',
            content: 'Weekly meditation sessions focusing on different techniques each week. Peaceful environment with guided instruction. Meditation cushions and props provided.',
            image_url: '/images/meditation.jpg',
            location: 'Community Center Quiet Space',
            date: '2025-10-27',
            start_time: '17:30',
            end_time: '18:30',
            address: '789 Community Way, Meditation Room',
            category_id: 2
        },
        {
            title: 'Heart Health Education Seminar',
            description: 'Learn about maintaining cardiovascular health',
            content: 'Educational seminar covering heart-healthy lifestyle choices, warning signs to watch for, and prevention strategies. Presented by cardiologist and cardiac nurses.',
            image_url: '/images/heart-health.jpg',
            location: 'Excel Centre Conference Room',
            date: '2025-10-30',
            start_time: '19:00',
            end_time: '20:30',
            address: '100 Excel Centre Drive, Conference Hall A',
            category_id: 2
        },
        {
            title: 'Healthy Cooking Demonstration',
            description: 'Learn to prepare nutritious and delicious meals',
            content: 'Professional chef demonstrates healthy cooking techniques with focus on heart-healthy and diabetic-friendly recipes. Participants receive recipe booklet and food samples.',
            image_url: '/images/healthy-cooking.jpg',
            location: 'Community Center Teaching Kitchen',
            date: '2025-11-03',
            start_time: '15:00',
            end_time: '17:00',
            address: '789 Community Way, Culinary Center',
            category_id: 2
        },
        {
            title: 'Sleep Hygiene Workshop',
            description: 'Improve your sleep quality with proven techniques',
            content: 'Learn about the importance of quality sleep and practical strategies for better rest. Covers sleep environment optimization, bedtime routines, and addressing common sleep issues.',
            image_url: '/images/sleep-hygiene.jpg',
            location: 'Community Center Classroom B',
            date: '2025-11-06',
            start_time: '18:00',
            end_time: '19:30',
            address: '789 Community Way, Education Wing Room B',
            category_id: 2
        },
        {
            title: 'Diabetes Management Support Group',
            description: 'Support and education for individuals managing diabetes',
            content: 'Monthly support group for individuals with diabetes and their families. Topics include blood sugar management, nutrition planning, and lifestyle adaptations.',
            image_url: '/images/diabetes-support.jpg',
            location: 'Stratford Health Center Meeting Room',
            date: '2025-11-10',
            start_time: '14:00',
            end_time: '15:30',
            address: 'Stratford Shopping Centre, Health Center Room 3',
            category_id: 2
        },
        {
            title: 'Women\'s Health Information Session',
            description: 'Health topics specifically relevant to women',
            content: 'Informational session covering womens health screenings, preventive care, and wellness strategies. Presented by womens health specialists.',
            image_url: '/images/womens-health.jpg',
            location: 'Excel Centre Private Conference Room',
            date: '2025-11-13',
            start_time: '19:00',
            end_time: '20:30',
            address: '100 Excel Centre Drive, Private Meeting Room',
            category_id: 2
        },
        {
            title: 'First Aid and CPR Training',
            description: 'Learn life-saving first aid and CPR techniques',
            content: 'Certified first aid and CPR training course. Participants receive certification upon completion. Essential skills for family safety and community emergency response.',
            image_url: '/images/first-aid.jpg',
            location: 'Community Center Training Room',
            date: '2025-11-17',
            start_time: '09:00',
            end_time: '16:00',
            address: '789 Community Way, Training Facility',
            category_id: 2
        },
        {
            title: 'Addiction Recovery Support Circle',
            description: 'Support group for individuals in recovery',
            content: 'Confidential support group for individuals recovering from various addictions. Peer support and professional guidance available in a non-judgmental environment.',
            image_url: '/images/addiction-recovery.jpg',
            location: 'Community Center Private Room',
            date: '2025-11-20',
            start_time: '19:00',
            end_time: '20:30',
            address: '789 Community Way, Counseling Center',
            category_id: 2
        },
        {
            title: 'Seasonal Affective Disorder Workshop',
            description: 'Coping strategies for seasonal depression',
            content: 'Educational workshop about seasonal affective disorder, its symptoms, and evidence-based treatment options. Light therapy demonstration and resources provided.',
            image_url: '/images/sad-workshop.jpg',
            location: 'Excel Centre Wellness Room',
            date: '2025-11-24',
            start_time: '16:00',
            end_time: '17:30',
            address: '100 Excel Centre Drive, Wellness Center',
            category_id: 2
        },
        {
            title: 'Posture and Ergonomics Clinic',
            description: 'Improve your posture and prevent workplace injuries',
            content: 'Assessment of posture and workspace ergonomics with personalized recommendations. Exercises and stretches for common problem areas demonstrated.',
            image_url: '/images/posture-clinic.jpg',
            location: 'Stratford Physical Therapy Center',
            date: '2025-11-27',
            start_time: '18:00',
            end_time: '19:30',
            address: 'Stratford Shopping Centre, Therapy Wing',
            category_id: 2
        },
        {
            title: 'Blood Donation Drive',
            description: 'Community blood donation event saving lives',
            content: 'Partner with local blood bank for community donation drive. Professional medical staff on-site. Refreshments provided for all donors. Help save lives in your community.',
            image_url: '/images/blood-donation.jpg',
            location: 'Community Center Main Hall',
            date: '2025-12-01',
            start_time: '10:00',
            end_time: '16:00',
            address: '789 Community Way, Main Hall',
            category_id: 2
        },
        {
            title: 'Aging Gracefully Seminar',
            description: 'Healthy aging strategies and resources',
            content: 'Seminar covering physical, mental, and social aspects of healthy aging. Topics include exercise, nutrition, social connections, and available community resources.',
            image_url: '/images/aging-gracefully.jpg',
            location: 'Excel Centre Senior Center',
            date: '2025-12-04',
            start_time: '14:00',
            end_time: '16:00',
            address: '100 Excel Centre Drive, Senior Activity Center',
            category_id: 2
        },
        {
            title: 'Alternative Medicine Information Fair',
            description: 'Explore complementary and alternative health approaches',
            content: 'Information fair featuring various alternative medicine practitioners including acupuncture, massage therapy, herbal medicine, and chiropractic care.',
            image_url: '/images/alternative-medicine.jpg',
            location: 'Community Center Exhibition Hall',
            date: '2025-12-08',
            start_time: '11:00',
            end_time: '15:00',
            address: '789 Community Way, Exhibition Space',
            category_id: 2
        },
        {
            title: 'New Year Wellness Challenge Launch',
            description: 'Start the new year with healthy goals and community support',
            content: 'Launch event for community-wide wellness challenge. Goal setting workshop, fitness assessments, and team formation for ongoing support and accountability.',
            image_url: '/images/wellness-challenge.jpg',
            location: 'Excel Centre Fitness Center',
            date: '2025-12-11',
            start_time: '18:30',
            end_time: '20:00',
            address: '100 Excel Centre Drive, Fitness Complex',
            category_id: 2
        },

        // Education & Learning (Category 3) - 20 events
        {
            title: 'Adult Computer Skills Workshop',
            description: 'Learn essential computer skills for daily life and work',
            content: 'Beginner-friendly workshop covering basic computer operations, internet browsing, email, and common software applications. Individual assistance available.',
            image_url: '/images/computer-skills.jpg',
            location: 'Community Center Computer Lab',
            date: '2025-10-07',
            start_time: '18:00',
            end_time: '20:00',
            address: '789 Community Way, Computer Learning Center',
            category_id: 3
        },
        {
            title: 'Children\'s Reading Circle',
            description: 'Fun reading sessions for children ages 4-10',
            content: 'Interactive storytelling sessions with games, crafts, and discussion. Helps develop reading skills and love for books in a fun, social environment.',
            image_url: '/images/reading-circle.jpg',
            location: 'Community Center Children\'s Room',
            date: '2025-10-11',
            start_time: '16:00',
            end_time: '17:00',
            address: '789 Community Way, Children\'s Library',
            category_id: 3
        },
        {
            title: 'Language Exchange Program',
            description: 'Practice speaking different languages with native speakers',
            content: 'Weekly language exchange sessions pairing native speakers with learners. Currently supporting English, Spanish, French, and Mandarin conversations.',
            image_url: '/images/language-exchange.jpg',
            location: 'Excel Centre Meeting Rooms',
            date: '2025-10-14',
            start_time: '19:00',
            end_time: '20:30',
            address: '100 Excel Centre Drive, International Center',
            category_id: 3
        },
        {
            title: 'Career Development Seminar',
            description: 'Build skills for career advancement and job searching',
            content: 'Professional development workshop covering resume writing, interview skills, networking strategies, and career planning. Guest speakers from various industries.',
            image_url: '/images/career-development.jpg',
            location: 'Stratford Business Center',
            date: '2025-10-17',
            start_time: '18:30',
            end_time: '21:00',
            address: 'Stratford Shopping Centre, Business Development Wing',
            category_id: 3
        },
        {
            title: 'Financial Literacy Workshop',
            description: 'Learn essential personal finance skills',
            content: 'Practical workshop covering budgeting, saving, debt management, and basic investing principles. Free workbooks and ongoing resources provided.',
            image_url: '/images/financial-literacy.jpg',
            location: 'Community Center Conference Room',
            date: '2025-10-21',
            start_time: '19:00',
            end_time: '21:00',
            address: '789 Community Way, Education Center',
            category_id: 3
        },
        {
            title: 'Creative Writing Workshop',
            description: 'Develop your writing skills in a supportive environment',
            content: 'Weekly writing workshop for aspiring writers of all levels. Exercises, prompts, and constructive feedback help improve writing skills and creativity.',
            image_url: '/images/creative-writing.jpg',
            location: 'Arts Center Writing Studio',
            date: '2025-10-24',
            start_time: '18:00',
            end_time: '20:00',
            address: '321 Arts Boulevard, Creative Writing Room',
            category_id: 3
        },
        {
            title: 'Digital Photography Masterclass',
            description: 'Advanced photography techniques and editing skills',
            content: 'Learn composition, lighting, and post-processing techniques from professional photographers. Bring your camera and laptop for hands-on practice.',
            image_url: '/images/photography-masterclass.jpg',
            location: 'Excel Centre Media Lab',
            date: '2025-10-28',
            start_time: '13:00',
            end_time: '17:00',
            address: '100 Excel Centre Drive, Digital Media Center',
            category_id: 3
        },
        {
            title: 'Parenting Skills Workshop',
            description: 'Practical strategies for effective parenting',
            content: 'Workshop covering communication strategies, discipline techniques, and age-appropriate expectations. Suitable for parents of children of all ages.',
            image_url: '/images/parenting-skills.jpg',
            location: 'Community Center Family Room',
            date: '2025-10-31',
            start_time: '19:00',
            end_time: '21:00',
            address: '789 Community Way, Family Support Center',
            category_id: 3
        },
        {
            title: 'Home Repair and Maintenance Class',
            description: 'Learn basic home maintenance and repair skills',
            content: 'Hands-on workshop covering plumbing basics, electrical safety, painting techniques, and general home maintenance. Tools and materials provided.',
            image_url: '/images/home-repair.jpg',
            location: 'Stratford Workshop Space',
            date: '2025-11-04',
            start_time: '18:00',
            end_time: '21:00',
            address: 'Stratford Shopping Centre, Workshop Area',
            category_id: 3
        },
        {
            title: 'Coding for Beginners',
            description: 'Introduction to computer programming',
            content: 'Learn basic programming concepts using beginner-friendly languages. No prior experience necessary. Laptops provided or bring your own.',
            image_url: '/images/coding-beginners.jpg',
            location: 'Excel Centre Tech Lab',
            date: '2025-11-07',
            start_time: '18:30',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Technology Learning Center',
            category_id: 3
        },
        {
            title: 'Nutrition and Meal Planning Workshop',
            description: 'Learn to plan healthy, budget-friendly meals',
            content: 'Practical nutrition education with meal planning strategies, grocery shopping tips, and batch cooking techniques. Recipe cards and meal plans included.',
            image_url: '/images/meal-planning.jpg',
            location: 'Community Center Teaching Kitchen',
            date: '2025-11-11',
            start_time: '14:00',
            end_time: '17:00',
            address: '789 Community Way, Culinary Education Center',
            category_id: 3
        },
        {
            title: 'Public Speaking and Presentation Skills',
            description: 'Overcome fear of public speaking and improve presentation abilities',
            content: 'Interactive workshop covering speech preparation, delivery techniques, and managing presentation anxiety. Practice opportunities with supportive feedback.',
            image_url: '/images/public-speaking.jpg',
            location: 'Excel Centre Auditorium',
            date: '2025-11-14',
            start_time: '18:00',
            end_time: '20:30',
            address: '100 Excel Centre Drive, Main Auditorium',
            category_id: 3
        },
        {
            title: 'Senior Technology Training',
            description: 'Technology skills specifically designed for seniors',
            content: 'Patient, senior-focused instruction on smartphones, tablets, video calling, and staying connected with family online. Individual assistance available.',
            image_url: '/images/senior-tech.jpg',
            location: 'Community Center Senior Lab',
            date: '2025-11-18',
            start_time: '10:00',
            end_time: '12:00',
            address: '789 Community Way, Senior Technology Center',
            category_id: 3
        },
        {
            title: 'Study Skills for Students',
            description: 'Effective study techniques and time management',
            content: 'Workshop for students of all ages covering note-taking, test preparation, time management, and stress reduction during exams. Study aids provided.',
            image_url: '/images/study-skills.jpg',
            location: 'Stratford Study Center',
            date: '2025-11-21',
            start_time: '16:00',
            end_time: '18:00',
            address: 'Stratford Shopping Centre, Student Learning Hub',
            category_id: 3
        },
        {
            title: 'Entrepreneurship Basics Workshop',
            description: 'Learn the fundamentals of starting your own business',
            content: 'Introduction to business planning, market research, financing options, and legal considerations for new entrepreneurs. Guest speakers and networking opportunities.',
            image_url: '/images/entrepreneurship.jpg',
            location: 'Excel Centre Business Incubator',
            date: '2025-11-25',
            start_time: '19:00',
            end_time: '21:30',
            address: '100 Excel Centre Drive, Business Development Center',
            category_id: 3
        },
        {
            title: 'Art History Appreciation Course',
            description: 'Explore major art movements and famous artists',
            content: 'Six-week course covering Western art history from Renaissance to modern times. Includes virtual museum tours and local gallery visits.',
            image_url: '/images/art-history.jpg',
            location: 'Arts Center Lecture Hall',
            date: '2025-11-28',
            start_time: '19:00',
            end_time: '20:30',
            address: '321 Arts Boulevard, Education Wing',
            category_id: 3
        },
        {
            title: 'Basic Auto Maintenance Workshop',
            description: 'Learn essential car maintenance skills',
            content: 'Hands-on workshop covering oil changes, tire rotation, fluid checks, and basic troubleshooting. Tools provided, wear old clothes.',
            image_url: '/images/auto-maintenance.jpg',
            location: 'Community Garage Workshop',
            date: '2025-12-02',
            start_time: '09:00',
            end_time: '13:00',
            address: '456 Industrial Drive, Community Workshop',
            category_id: 3
        },
        {
            title: 'Mindfulness and Meditation Training',
            description: 'Learn meditation techniques for stress reduction and focus',
            content: 'Eight-week mindfulness program teaching various meditation techniques, stress reduction, and improving focus and emotional regulation.',
            image_url: '/images/mindfulness-training.jpg',
            location: 'Community Center Meditation Space',
            date: '2025-12-05',
            start_time: '18:00',
            end_time: '19:30',
            address: '789 Community Way, Wellness Center',
            category_id: 3
        },
        {
            title: 'College Preparation Workshop',
            description: 'Guidance for students planning for higher education',
            content: 'Workshop covering college applications, financial aid, scholarship opportunities, and academic preparation. For high school students and parents.',
            image_url: '/images/college-prep.jpg',
            location: 'Stratford Education Center',
            date: '2025-12-09',
            start_time: '18:30',
            end_time: '21:00',
            address: 'Stratford Shopping Centre, Education Services Wing',
            category_id: 3
        },
        {
            title: 'History of Our Community Lecture Series',
            description: 'Explore the rich history and heritage of our local area',
            content: 'Monthly lecture series featuring local historians and long-time residents sharing stories, photos, and artifacts from our communitys past.',
            image_url: '/images/community-history.jpg',
            location: 'Excel Centre Heritage Room',
            date: '2025-12-12',
            start_time: '19:00',
            end_time: '20:30',
            address: '100 Excel Centre Drive, Heritage Center',
            category_id: 3
        },

        // Arts & Culture (Category 4) - 20 events
        {
            title: 'Community Art Exhibition Opening',
            description: 'Showcasing local artists and their latest works',
            content: 'Annual exhibition featuring paintings, sculptures, photography, and mixed media from community artists. Opening reception includes artist meet-and-greet and light refreshments.',
            image_url: '/images/art-exhibition.jpg',
            location: 'Arts Center Main Gallery',
            date: '2025-10-08',
            start_time: '19:00',
            end_time: '21:00',
            address: '321 Arts Boulevard, Main Exhibition Hall',
            category_id: 4
        },
        {
            title: 'Local Music Night',
            description: 'Featuring talented musicians from our community',
            content: 'Monthly showcase of local musical talent across all genres. Open mic opportunities available for emerging artists. Family-friendly environment with café seating.',
            image_url: '/images/music-night.jpg',
            location: 'Excel Centre Performance Stage',
            date: '2025-10-11',
            start_time: '20:00',
            end_time: '23:00',
            address: '100 Excel Centre Drive, Main Performance Hall',
            category_id: 4
        },
        {
            title: 'Pottery Classes for Beginners',
            description: 'Learn the ancient art of pottery making',
            content: 'Six-week pottery course covering basic techniques, glazing, and firing. All materials included, and participants keep their finished pieces.',
            image_url: '/images/pottery-class.jpg',
            location: 'Arts Center Pottery Studio',
            date: '2025-10-15',
            start_time: '18:30',
            end_time: '20:30',
            address: '321 Arts Boulevard, Ceramics Workshop',
            category_id: 4
        },
        {
            title: 'Drama Club Performance: Shakespeare Night',
            description: 'Local theater group performs classic Shakespeare scenes',
            content: 'Community drama club presents selected scenes from various Shakespeare plays. Audience participation encouraged for some segments. Light medieval refreshments served.',
            image_url: '/images/shakespeare-night.jpg',
            location: 'Community Center Theater',
            date: '2025-10-18',
            start_time: '19:30',
            end_time: '21:30',
            address: '789 Community Way, Community Theater',
            category_id: 4
        },
        {
            title: 'Cultural Heritage Festival',
            description: 'Celebrating the diverse cultures in our community',
            content: 'Multi-cultural festival featuring traditional foods, music, dance, and crafts from various cultures represented in our community. International food vendors and cultural displays.',
            image_url: '/images/heritage-festival.jpg',
            location: 'Central Park Festival Grounds',
            date: '2025-10-22',
            start_time: '11:00',
            end_time: '18:00',
            address: 'Central Park, Main Festival Area',
            category_id: 4
        },
        {
            title: 'Photography Exhibition: "Our Community Through the Lens"',
            description: 'Photo exhibition capturing life in our community',
            content: 'Photography exhibition featuring works by local photographers showcasing daily life, landscapes, and people of our community. Voting for peoples choice award.',
            image_url: '/images/photo-exhibition.jpg',
            location: 'Stratford Gallery Space',
            date: '2025-10-25',
            start_time: '10:00',
            end_time: '17:00',
            address: 'Stratford Shopping Centre, Gallery Wing',
            category_id: 4
        },
        {
            title: 'Watercolor Painting Workshop',
            description: 'Learn watercolor techniques with local artist instructor',
            content: 'Hands-on watercolor workshop suitable for all skill levels. Focus on landscape painting techniques. All materials provided including paints, brushes, and paper.',
            image_url: '/images/watercolor-workshop.jpg',
            location: 'Arts Center Painting Studio',
            date: '2025-10-29',
            start_time: '14:00',
            end_time: '17:00',
            address: '321 Arts Boulevard, Painting Workshop Room',
            category_id: 4
        },
        {
            title: 'Community Choir Concert',
            description: 'Our local choir performs seasonal favorites',
            content: 'Community choir presents a concert of classical pieces, folk songs, and contemporary favorites. Guest soloists and small ensemble performances included.',
            image_url: '/images/choir-concert.jpg',
            location: 'Excel Centre Concert Hall',
            date: '2025-11-01',
            start_time: '19:30',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Main Concert Hall',
            category_id: 4
        },
        {
            title: 'Sculpture in the Park Installation',
            description: 'New outdoor sculpture installation and artist talk',
            content: 'Unveiling of new outdoor sculpture installation with artist presentation about the creative process and inspiration. Guided tours available.',
            image_url: '/images/sculpture-park.jpg',
            location: 'Central Park Sculpture Garden',
            date: '2025-11-05',
            start_time: '15:00',
            end_time: '16:30',
            address: 'Central Park, Sculpture Garden Area',
            category_id: 4
        },
        {
            title: 'Folk Dance Workshop and Social',
            description: 'Learn traditional folk dances from around the world',
            content: 'Interactive workshop teaching folk dances from various cultures followed by social dancing. No partner or experience necessary. Traditional costumes welcome but not required.',
            image_url: '/images/folk-dance.jpg',
            location: 'Community Center Dance Hall',
            date: '2025-11-08',
            start_time: '19:00',
            end_time: '21:30',
            address: '789 Community Way, Main Dance Hall',
            category_id: 4
        },
        {
            title: 'Creative Writing Reading Night',
            description: 'Local writers share their original works',
            content: 'Open mic night for local writers to share poetry, short stories, and excerpts from longer works. Supportive audience and constructive feedback environment.',
            image_url: '/images/writing-reading.jpg',
            location: 'Arts Center Literary Lounge',
            date: '2025-11-12',
            start_time: '19:30',
            end_time: '21:00',
            address: '321 Arts Boulevard, Writers Room',
            category_id: 4
        },
        {
            title: 'Jazz Appreciation Evening',
            description: 'Learn about and listen to classic and contemporary jazz',
            content: 'Educational and entertaining evening exploring jazz history with live performances by local jazz musicians. Wine and cheese reception included.',
            image_url: '/images/jazz-evening.jpg',
            location: 'Excel Centre Jazz Lounge',
            date: '2025-11-15',
            start_time: '20:00',
            end_time: '22:30',
            address: '100 Excel Centre Drive, Intimate Performance Space',
            category_id: 4
        },
        {
            title: 'Craft Fair and Artisan Market',
            description: 'Local artisans showcase and sell their handmade creations',
            content: 'Monthly craft fair featuring local artisans selling handmade jewelry, textiles, woodworking, and other crafts. Meet the makers and learn about their techniques.',
            image_url: '/images/craft-fair.jpg',
            location: 'Stratford Market Hall',
            date: '2025-11-19',
            start_time: '10:00',
            end_time: '16:00',
            address: 'Stratford Shopping Centre, Market Hall',
            category_id: 4
        },
        {
            title: 'Film Screening: Local Documentary Premiere',
            description: 'Premiere of documentary about our community history',
            content: 'Exclusive screening of locally-produced documentary exploring our communitys development over the past 50 years. Q&A session with filmmakers follows screening.',
            image_url: '/images/film-screening.jpg',
            location: 'Community Center Auditorium',
            date: '2025-11-22',
            start_time: '19:00',
            end_time: '21:00',
            address: '789 Community Way, Main Auditorium',
            category_id: 4
        },
        {
            title: 'Holiday Decoration Workshop',
            description: 'Create beautiful decorations for the holiday season',
            content: 'Family-friendly workshop creating handmade holiday decorations using natural and recycled materials. Take home decorations for your own celebration.',
            image_url: '/images/holiday-decorations.jpg',
            location: 'Arts Center Craft Studio',
            date: '2025-11-26',
            start_time: '14:00',
            end_time: '17:00',
            address: '321 Arts Boulevard, Multi-Purpose Craft Room',
            category_id: 4
        },
        {
            title: 'Street Art and Mural Walking Tour',
            description: 'Guided tour of local street art and murals',
            content: 'Walking tour exploring the outdoor art installations and murals throughout our community. Learn about the artists and stories behind each piece.',
            image_url: '/images/street-art-tour.jpg',
            location: 'Meet at Central Park Main Entrance',
            date: '2025-11-29',
            start_time: '14:00',
            end_time: '16:00',
            address: 'Central Park Main Entrance, Begin Walking Tour',
            category_id: 4
        },
        {
            title: 'Community Theater Auditions',
            description: 'Open auditions for upcoming community theater production',
            content: 'Auditions for all roles in upcoming spring production. No experience necessary - we welcome newcomers! Technical crew positions also available.',
            image_url: '/images/theater-auditions.jpg',
            location: 'Community Center Theater',
            date: '2025-12-03',
            start_time: '18:00',
            end_time: '21:00',
            address: '789 Community Way, Main Theater',
            category_id: 4
        },
        {
            title: 'Traditional Crafts Workshop: Basket Weaving',
            description: 'Learn the traditional art of basket weaving',
            content: 'Hands-on workshop learning traditional basket weaving techniques. All materials provided including reed and tools. Participants complete a small basket to take home.',
            image_url: '/images/basket-weaving.jpg',
            location: 'Arts Center Traditional Crafts Room',
            date: '2025-12-06',
            start_time: '13:00',
            end_time: '17:00',
            address: '321 Arts Boulevard, Heritage Crafts Workshop',
            category_id: 4
        },
        {
            title: 'Winter Solstice Celebration',
            description: 'Community celebration marking the winter solstice',
            content: 'Traditional winter solstice celebration with lantern lighting, storytelling, seasonal music, and warm refreshments. Family-friendly outdoor event.',
            image_url: '/images/winter-solstice.jpg',
            location: 'Central Park Amphitheater',
            date: '2025-12-10',
            start_time: '17:00',
            end_time: '19:00',
            address: 'Central Park, Natural Amphitheater Area',
            category_id: 4
        },
        {
            title: 'Year-End Art Student Showcase',
            description: 'Students from community art classes display their best works',
            content: 'Exhibition showcasing artwork created by students in community art classes throughout the year. All mediums represented including painting, sculpture, and digital art.',
            image_url: '/images/student-showcase.jpg',
            location: 'Excel Centre Gallery Space',
            date: '2025-12-13',
            start_time: '18:00',
            end_time: '20:00',
            address: '100 Excel Centre Drive, Student Gallery',
            category_id: 4
        },

        // Environment & Sustainability (Category 5) - 20 events
        {
            title: 'Community Garden Project Launch',
            description: 'Start or expand our community garden initiative',
            content: 'Community meeting to plan new garden plots, assign responsibilities, and organize seasonal planting schedules. Plot rental information and gardening resources provided.',
            image_url: '/images/garden-project.jpg',
            location: 'Community Garden Site',
            date: '2025-10-09',
            start_time: '10:00',
            end_time: '13:00',
            address: '654 Greenfield Avenue, Community Garden',
            category_id: 5
        },
        {
            title: 'Monthly Recycling Drive',
            description: 'Community-wide recycling collection event',
            content: 'Bring electronics, batteries, hazardous materials, and other special recycling items. Education about proper disposal and waste reduction strategies.',
            image_url: '/images/recycling-drive.jpg',
            location: 'Excel Centre Parking Area',
            date: '2025-10-12',
            start_time: '09:00',
            end_time: '15:00',
            address: '100 Excel Centre Drive, North Parking Lot',
            category_id: 5
        },
        {
            title: 'Tree Planting Event',
            description: 'Help plant trees to beautify and improve our environment',
            content: 'Community tree planting event focusing on native species. Tools provided, but bring gloves and water. Educational component about local ecosystems included.',
            image_url: '/images/tree-planting.jpg',
            location: 'Central Park Restoration Area',
            date: '2025-10-16',
            start_time: '08:30',
            end_time: '12:00',
            address: 'Central Park, North Restoration Zone',
            category_id: 5
        },
        {
            title: 'Sustainability Workshop: Reduce, Reuse, Recycle',
            description: 'Learn practical ways to live more sustainably',
            content: 'Workshop covering waste reduction, upcycling projects, energy conservation, and sustainable shopping practices. Take-home guides and resources provided.',
            image_url: '/images/sustainability-workshop.jpg',
            location: 'Community Center Green Room',
            date: '2025-10-19',
            start_time: '14:00',
            end_time: '16:30',
            address: '789 Community Way, Environmental Education Center',
            category_id: 5
        },
        {
            title: 'Community Clean-up Day',
            description: 'Monthly neighborhood beautification effort',
            content: 'Community-wide clean-up focusing on parks, streets, and public spaces. Supplies provided including gloves, bags, and picking tools. Refreshments for all volunteers.',
            image_url: '/images/cleanup-day.jpg',
            location: 'Meet at Community Center',
            date: '2025-10-23',
            start_time: '08:00',
            end_time: '12:00',
            address: '789 Community Way, Volunteer Coordination Center',
            category_id: 5
        },
        {
            title: 'Composting Workshop',
            description: 'Learn to create nutrient-rich compost for your garden',
            content: 'Hands-on workshop covering composting basics, bin construction, and troubleshooting common problems. Participants receive starter materials and instruction guide.',
            image_url: '/images/composting-workshop.jpg',
            location: 'Community Garden Education Pavilion',
            date: '2025-10-26',
            start_time: '11:00',
            end_time: '13:00',
            address: '654 Greenfield Avenue, Garden Learning Center',
            category_id: 5
        },
        {
            title: 'Native Plant Sale and Information Fair',
            description: 'Purchase native plants and learn about local ecosystems',
            content: 'Annual sale of native plants with expert advice on selection and care. Educational displays about local wildlife and ecosystem preservation.',
            image_url: '/images/native-plant-sale.jpg',
            location: 'Stratford Garden Center',
            date: '2025-10-30',
            start_time: '09:00',
            end_time: '16:00',
            address: 'Stratford Shopping Centre, Garden Center',
            category_id: 5
        },
        {
            title: 'Energy Conservation Home Audit Workshop',
            description: 'Learn to assess and improve your homes energy efficiency',
            content: 'Workshop teaching homeowners how to conduct energy audits, identify problem areas, and implement cost-effective improvements. Tools and checklists provided.',
            image_url: '/images/energy-audit.jpg',
            location: 'Excel Centre Conservation Lab',
            date: '2025-11-02',
            start_time: '10:00',
            end_time: '14:00',
            address: '100 Excel Centre Drive, Energy Education Center',
            category_id: 5
        },
        {
            title: 'Pollinator Garden Design Workshop',
            description: 'Create gardens that support bees, butterflies, and other pollinators',
            content: 'Learn to design and plant gardens that attract and support local pollinators. Plant selection guides and garden planning materials included.',
            image_url: '/images/pollinator-garden.jpg',
            location: 'Arts Center Outdoor Classroom',
            date: '2025-11-06',
            start_time: '13:00',
            end_time: '16:00',
            address: '321 Arts Boulevard, Outdoor Learning Space',
            category_id: 5
        },
        {
            title: 'Water Conservation Techniques Workshop',
            description: 'Learn methods to reduce water usage at home and in gardens',
            content: 'Practical workshop covering rain water harvesting, drought-resistant landscaping, and efficient irrigation methods. Demonstration garden tour included.',
            image_url: '/images/water-conservation.jpg',
            location: 'Community Garden Demonstration Area',
            date: '2025-11-09',
            start_time: '14:00',
            end_time: '16:30',
            address: '654 Greenfield Avenue, Demo Garden',
            category_id: 5
        },
        {
            title: 'Sustainable Transportation Fair',
            description: 'Explore eco-friendly transportation options',
            content: 'Information fair featuring electric vehicles, bicycles, public transit options, and car-sharing programs. Test drives and demonstrations available.',
            image_url: '/images/sustainable-transport.jpg',
            location: 'Central Park Event Space',
            date: '2025-11-13',
            start_time: '10:00',
            end_time: '15:00',
            address: 'Central Park, Main Event Area',
            category_id: 5
        },
        {
            title: 'Climate Change Impact Discussion',
            description: 'Community discussion on local climate change effects and adaptations',
            content: 'Educational session about climate change impacts on our local area and community strategies for adaptation and mitigation. Expert speakers and open discussion.',
            image_url: '/images/climate-discussion.jpg',
            location: 'Community Center Main Hall',
            date: '2025-11-16',
            start_time: '19:00',
            end_time: '21:00',
            address: '789 Community Way, Conference Hall',
            category_id: 5
        },
        {
            title: 'Green Building and Renovation Fair',
            description: 'Learn about environmentally friendly building and renovation practices',
            content: 'Information fair featuring sustainable building materials, green renovation techniques, and energy-efficient home improvements. Contractor demonstrations included.',
            image_url: '/images/green-building.jpg',
            location: 'Excel Centre Exhibition Hall',
            date: '2025-11-20',
            start_time: '11:00',
            end_time: '17:00',
            address: '100 Excel Centre Drive, Main Exhibition Space',
            category_id: 5
        },
        {
            title: 'Urban Wildlife Protection Workshop',
            description: 'Learn how to protect and coexist with local wildlife',
            content: 'Workshop about local wildlife species, habitat protection, and creating wildlife-friendly spaces. Includes information about wildlife corridors and native landscaping.',
            image_url: '/images/wildlife-protection.jpg',
            location: 'Central Park Nature Center',
            date: '2025-11-23',
            start_time: '13:00',
            end_time: '15:30',
            address: 'Central Park, Wildlife Education Center',
            category_id: 5
        },
        {
            title: 'Eco-Friendly Cleaning Products Workshop',
            description: 'Make safe, effective cleaning products at home',
            content: 'Hands-on workshop creating natural cleaning products using common household ingredients. Recipes, ingredients, and containers provided to take home.',
            image_url: '/images/eco-cleaning.jpg',
            location: 'Community Center Workshop Room',
            date: '2025-11-27',
            start_time: '18:30',
            end_time: '20:30',
            address: '789 Community Way, Multi-Purpose Workshop Room',
            category_id: 5
        },
        {
            title: 'Solar Energy Information Session',
            description: 'Learn about residential solar energy options',
            content: 'Information session covering residential solar installation, costs, benefits, and local incentive programs. Solar installers available for consultations.',
            image_url: '/images/solar-energy.jpg',
            location: 'Stratford Conference Center',
            date: '2025-11-30',
            start_time: '15:00',
            end_time: '17:00',
            address: 'Stratford Shopping Centre, Conference Room B',
            category_id: 5
        },
        {
            title: 'Sustainable Fashion and Clothing Swap',
            description: 'Exchange gently used clothing and learn about sustainable fashion',
            content: 'Community clothing swap event with information about sustainable fashion choices, clothing care, and textile recycling. Bring clean clothing to exchange.',
            image_url: '/images/clothing-swap.jpg',
            location: 'Community Center Social Hall',
            date: '2025-12-04',
            start_time: '10:00',
            end_time: '15:00',
            address: '789 Community Way, Social Hall',
            category_id: 5
        },
        {
            title: 'Food Waste Reduction Workshop',
            description: 'Learn strategies to minimize household food waste',
            content: 'Workshop covering meal planning, proper food storage, creative use of leftovers, and composting food scraps. Recipe ideas and storage containers provided.',
            image_url: '/images/food-waste.jpg',
            location: 'Community Center Teaching Kitchen',
            date: '2025-12-07',
            start_time: '16:00',
            end_time: '18:30',
            address: '789 Community Way, Culinary Education Center',
            category_id: 5
        },
        {
            title: 'Sustainable Holiday Celebrations',
            description: 'Celebrate holidays in environmentally conscious ways',
            content: 'Workshop on reducing holiday waste through sustainable gift-giving, decoration ideas using natural materials, and eco-friendly celebration planning.',
            image_url: '/images/sustainable-holidays.jpg',
            location: 'Arts Center Event Room',
            date: '2025-12-11',
            start_time: '18:00',
            end_time: '20:00',
            address: '321 Arts Boulevard, Community Event Space',
            category_id: 5
        },
        {
            title: 'Year-End Environmental Impact Review',
            description: 'Review community environmental achievements and plan for next year',
            content: 'Community meeting reviewing environmental initiatives from the past year and planning goals for the upcoming year. Recognition of outstanding environmental efforts.',
            image_url: '/images/environmental-review.jpg',
            location: 'Excel Centre Auditorium',
            date: '2025-12-14',
            start_time: '19:00',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Main Auditorium',
            category_id: 5
        },

        // Social Services (Category 6) - 20 events
        {
            title: 'Food Bank Volunteer Training',
            description: 'Training session for new food bank volunteers',
            content: 'Comprehensive training covering food safety, client interaction, inventory management, and volunteer protocols. Ongoing volunteer opportunities available.',
            image_url: '/images/food-bank-training.jpg',
            location: 'Community Food Bank',
            date: '2025-10-10',
            start_time: '18:00',
            end_time: '20:30',
            address: '456 Service Drive, Community Food Bank',
            category_id: 6
        },
        {
            title: 'Senior Support Services Information Session',
            description: 'Learn about available services and support for seniors',
            content: 'Information session covering meal delivery, transportation services, health support, and social programs available for seniors in our community.',
            image_url: '/images/senior-support.jpg',
            location: 'Excel Centre Senior Services Wing',
            date: '2025-10-13',
            start_time: '14:00',
            end_time: '16:00',
            address: '100 Excel Centre Drive, Senior Services Center',
            category_id: 6
        },
        {
            title: 'Volunteer Coordination Meeting',
            description: 'Monthly meeting for community volunteer coordinators',
            content: 'Monthly coordination meeting for volunteer program leaders to share resources, coordinate efforts, and plan community service initiatives.',
            image_url: '/images/volunteer-coordination.jpg',
            location: 'Community Center Conference Room',
            date: '2025-10-17',
            start_time: '19:00',
            end_time: '20:30',
            address: '789 Community Way, Volunteer Services Office',
            category_id: 6
        },
        {
            title: 'Community Counseling Services Open House',
            description: 'Learn about available mental health and counseling resources',
            content: 'Open house introducing community counseling services, support groups, and mental health resources. Meet counselors and learn about available programs.',
            image_url: '/images/counseling-services.jpg',
            location: 'Stratford Wellness Center',
            date: '2025-10-20',
            start_time: '17:00',
            end_time: '19:00',
            address: 'Stratford Shopping Centre, Wellness Wing',
            category_id: 6
        },
        {
            title: 'Emergency Assistance Program Information',
            description: 'Learn about emergency financial and resource assistance',
            content: 'Information session about emergency assistance programs including financial aid, food assistance, housing support, and utility help for families in crisis.',
            image_url: '/images/emergency-assistance.jpg',
            location: 'Community Center Private Meeting Room',
            date: '2025-10-24',
            start_time: '16:00',
            end_time: '17:30',
            address: '789 Community Way, Social Services Office',
            category_id: 6
        },
        {
            title: 'Homeless Outreach Volunteer Training',
            description: 'Training for volunteers working with homeless population',
            content: 'Specialized training for volunteers interested in homeless outreach, including safety protocols, available resources, and effective communication strategies.',
            image_url: '/images/homeless-outreach.jpg',
            location: 'Excel Centre Training Room',
            date: '2025-10-27',
            start_time: '09:00',
            end_time: '15:00',
            address: '100 Excel Centre Drive, Social Services Training Center',
            category_id: 6
        },
        {
            title: 'Community Resource Fair',
            description: 'Comprehensive fair showcasing all available community services',
            content: 'Large-scale resource fair featuring information booths from all community service organizations, government agencies, and support programs available locally.',
            image_url: '/images/resource-fair.jpg',
            location: 'Central Park Community Pavilion',
            date: '2025-10-31',
            start_time: '10:00',
            end_time: '16:00',
            address: 'Central Park, Main Community Pavilion',
            category_id: 6
        },
        {
            title: 'Family Support Services Workshop',
            description: 'Resources and support for families facing challenges',
            content: 'Workshop covering family support services including parenting resources, childcare assistance, educational support, and family counseling options.',
            image_url: '/images/family-support.jpg',
            location: 'Community Center Family Resource Room',
            date: '2025-11-03',
            start_time: '13:00',
            end_time: '15:00',
            address: '789 Community Way, Family Services Center',
            category_id: 6
        },
        {
            title: 'Clothing Donation and Distribution Event',
            description: 'Community clothing drive and free distribution',
            content: 'Monthly clothing donation collection and free distribution event for community members in need. Volunteers needed for sorting and distribution.',
            image_url: '/images/clothing-donation.jpg',
            location: 'Stratford Community Center',
            date: '2025-11-07',
            start_time: '09:00',
            end_time: '15:00',
            address: 'Stratford Shopping Centre, Community Service Area',
            category_id: 6
        },
        {
            title: 'Youth Mentorship Program Launch',
            description: 'Launch of program matching adult mentors with at-risk youth',
            content: 'Information session and application process for new youth mentorship program. Training provided for potential mentors and support for participating youth.',
            image_url: '/images/youth-mentorship.jpg',
            location: 'Excel Centre Youth Services Wing',
            date: '2025-11-10',
            start_time: '18:00',
            end_time: '20:00',
            address: '100 Excel Centre Drive, Youth Development Center',
            category_id: 6
        },
        {
            title: 'Holiday Toy and Gift Collection',
            description: 'Annual toy drive for families in need during holidays',
            content: 'Community toy and gift collection ensuring all local children have presents during the holiday season. Volunteer opportunities for sorting and distribution.',
            image_url: '/images/toy-collection.jpg',
            location: 'Community Center Storage and Distribution Area',
            date: '2025-11-14',
            start_time: '10:00',
            end_time: '18:00',
            address: '789 Community Way, Holiday Distribution Center',
            category_id: 6
        },
        {
            title: 'Legal Aid Clinic',
            description: 'Free legal consultation and assistance for community members',
            content: 'Monthly legal aid clinic offering free consultations on housing, family law, immigration, and consumer issues. Appointments preferred but walk-ins welcome.',
            image_url: '/images/legal-aid.jpg',
            location: 'Stratford Legal Services Office',
            date: '2025-11-17',
            start_time: '09:00',
            end_time: '16:00',
            address: 'Stratford Shopping Centre, Legal Aid Office',
            category_id: 6
        },
        {
            title: 'Senior Companion Program Information',
            description: 'Learn about companion services for isolated seniors',
            content: 'Information session about programs matching volunteers with isolated seniors for regular visits, companionship, and light assistance with daily activities.',
            image_url: '/images/senior-companion.jpg',
            location: 'Excel Centre Senior Activity Center',
            date: '2025-11-21',
            start_time: '15:00',
            end_time: '16:30',
            address: '100 Excel Centre Drive, Senior Programs Office',
            category_id: 6
        },
        {
            title: 'Community Crisis Response Training',
            description: 'Training for volunteers in community crisis response',
            content: 'Training covering crisis intervention, resource coordination, and support strategies for community members facing various types of emergencies or crises.',
            image_url: '/images/crisis-response.jpg',
            location: 'Community Center Training Facility',
            date: '2025-11-24',
            start_time: '09:00',
            end_time: '16:00',
            address: '789 Community Way, Emergency Training Center',
            category_id: 6
        },
        {
            title: 'Disability Services Information Fair',
            description: 'Resources and services for community members with disabilities',
            content: 'Information fair highlighting services, accommodations, and support programs available for individuals with disabilities and their families.',
            image_url: '/images/disability-services.jpg',
            location: 'Excel Centre Accessible Meeting Space',
            date: '2025-11-28',
            start_time: '13:00',
            end_time: '17:00',
            address: '100 Excel Centre Drive, Accessibility Services Center',
            category_id: 6
        },
        {
            title: 'Immigration Services Workshop',
            description: 'Information and assistance for newcomers and immigrants',
            content: 'Workshop providing information about immigration services, citizenship processes, language learning resources, and cultural integration support programs.',
            image_url: '/images/immigration-services.jpg',
            location: 'Community Center Multicultural Room',
            date: '2025-12-01',
            start_time: '14:00',
            end_time: '17:00',
            address: '789 Community Way, Multicultural Services Center',
            category_id: 6
        },
        {
            title: 'Substance Abuse Support Group',
            description: 'Support group for individuals and families affected by substance abuse',
            content: 'Weekly support group meetings for individuals in recovery and family members affected by substance abuse. Professional facilitation and peer support.',
            image_url: '/images/substance-abuse-support.jpg',
            location: 'Stratford Counseling Center',
            date: '2025-12-05',
            start_time: '19:00',
            end_time: '20:30',
            address: 'Stratford Shopping Centre, Counseling Services Wing',
            category_id: 6
        },
        {
            title: 'Community Mediation Training',
            description: 'Training for volunteers in conflict resolution and mediation',
            content: 'Comprehensive training program for community members interested in becoming volunteer mediators for neighborhood disputes and community conflicts.',
            image_url: '/images/mediation-training.jpg',
            location: 'Excel Centre Conference Center',
            date: '2025-12-08',
            start_time: '09:00',
            end_time: '17:00',
            address: '100 Excel Centre Drive, Mediation Training Room',
            category_id: 6
        },
        {
            title: 'Housing Assistance Information Session',
            description: 'Information about housing assistance and support programs',
            content: 'Information session covering rental assistance, housing vouchers, first-time homebuyer programs, and resources for individuals facing housing insecurity.',
            image_url: '/images/housing-assistance.jpg',
            location: 'Community Center Social Services Office',
            date: '2025-12-12',
            start_time: '18:00',
            end_time: '19:30',
            address: '789 Community Way, Housing Services Department',
            category_id: 6
        },
        {
            title: 'Year-End Volunteer Appreciation Event',
            description: 'Celebration recognizing community volunteers and their contributions',
            content: 'Annual appreciation event celebrating the contributions of community volunteers with awards, recognition, refreshments, and planning for the upcoming year.',
            image_url: '/images/volunteer-appreciation.jpg',
            location: 'Excel Centre Banquet Hall',
            date: '2025-12-15',
            start_time: '18:00',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Main Banquet Hall',
            category_id: 6
        },

        // Shop Safe, Shop Local (Category 7) - 20 events
        {
            title: 'Local Business Showcase and Networking',
            description: 'Meet local business owners and discover community enterprises',
            content: 'Monthly networking event highlighting local businesses, their products and services. Opportunity for residents to meet business owners and learn about local offerings.',
            image_url: '/images/business-showcase.jpg',
            location: 'Stratford Shopping Centre Main Atrium',
            date: '2025-10-11',
            start_time: '18:00',
            end_time: '20:30',
            address: 'Stratford Shopping Centre, Central Atrium',
            category_id: 7
        },
        {
            title: 'Shop Local Campaign Launch',
            description: 'Kick off community-wide initiative to support local businesses',
            content: 'Launch event for shop local campaign featuring promotional materials, loyalty programs, and special offers from participating local businesses.',
            image_url: '/images/shop-local-launch.jpg',
            location: 'Central Park Business Pavilion',
            date: '2025-10-14',
            start_time: '11:00',
            end_time: '15:00',
            address: 'Central Park, Business Community Pavilion',
            category_id: 7
        },
        {
            title: 'New Business Registration Workshop',
            description: 'Help for entrepreneurs starting new local businesses',
            content: 'Workshop covering business registration, permits, licensing, and local regulations for new business owners. Resource packets and ongoing support information provided.',
            image_url: '/images/business-registration.jpg',
            location: 'Excel Centre Business Development Office',
            date: '2025-10-18',
            start_time: '19:00',
            end_time: '21:00',
            address: '100 Excel Centre Drive, Business Services Center',
            category_id: 7
        },
        {
            title: 'Meet Your Neighbors: Home-Based Business Fair',
            description: 'Showcase of home-based businesses and neighborhood entrepreneurs',
            content: 'Fair featuring home-based businesses including crafters, consultants, food producers, and service providers. Meet your entrepreneurial neighbors.',
            image_url: '/images/home-business-fair.jpg',
            location: 'Community Center Exhibition Hall',
            date: '2025-10-21',
            start_time: '10:00',
            end_time: '16:00',
            address: '789 Community Way, Main Exhibition Space',
            category_id: 7
        },
        {
            title: 'Safe Shopping Practices Workshop',
            description: 'Learn about safe shopping in-person and online',
            content: 'Workshop covering safe shopping practices including fraud prevention, secure online shopping, and how to verify legitimate local businesses.',
            image_url: '/images/safe-shopping.jpg',
            location: 'Stratford Consumer Education Center',
            date: '2025-10-25',
            start_time: '18:30',
            end_time: '20:00',
            address: 'Stratford Shopping Centre, Consumer Services Wing',
            category_id: 7
        },
        {
            title: 'Local Farmers and Producers Market',
            description: 'Weekly market featuring local farmers and food producers',
            content: 'Weekly farmers market with local produce, baked goods, preserves, and artisanal food products. Meet the people who grow and make your food.',
            image_url: '/images/farmers-market.jpg',
            location: 'Central Park Market Square',
            date: '2025-10-28',
            start_time: '08:00',
            end_time: '14:00',
            address: 'Central Park, Designated Market Area',
            category_id: 7
        },
        {
            title: 'Small Business Saturday Celebration',
            description: 'Community celebration supporting local small businesses',
            content: 'Special event promoting local small businesses with extended hours, special offers, live entertainment, and community activities throughout the shopping areas.',
            image_url: '/images/small-business-saturday.jpg',
            location: 'Multiple Local Business Locations',
            date: '2025-11-01',
            start_time: '09:00',
            end_time: '18:00',
            address: 'Various Local Business Locations',
            category_id: 7
        },
        {
            title: 'Business Owner Mentorship Program',
            description: 'Pairing experienced business owners with new entrepreneurs',
            content: 'Program launch connecting established business owners with new entrepreneurs for ongoing mentorship, advice, and business development support.',
            image_url: '/images/business-mentorship.jpg',
            location: 'Excel Centre Business Incubator',
            date: '2025-11-04',
            start_time: '18:00',
            end_time: '20:00',
            address: '100 Excel Centre Drive, Entrepreneurship Center',
            category_id: 7
        },
        {
            title: 'Local Artisan Holiday Market',
            description: 'Holiday shopping featuring local artisans and crafters',
            content: 'Special holiday market featuring handmade gifts, decorations, and seasonal items created by local artisans. Perfect for unique holiday shopping.',
            image_url: '/images/artisan-holiday-market.jpg',
            location: 'Stratford Market Hall',
            date: '2025-11-08',
            start_time: '10:00',
            end_time: '17:00',
            address: 'Stratford Shopping Centre, Holiday Market Hall',
            category_id: 7
        },
        {
            title: 'Consumer Rights and Protection Workshop',
            description: 'Learn about consumer rights and how to resolve disputes',
            content: 'Educational workshop covering consumer rights, return policies, warranty protections, and how to resolve disputes with local businesses.',
            image_url: '/images/consumer-rights.jpg',
            location: 'Community Center Legal Education Room',
            date: '2025-11-11',
            start_time: '19:00',
            end_time: '20:30',
            address: '789 Community Way, Consumer Education Center',
            category_id: 7
        },
        {
            title: 'Local Business Directory and App Launch',
            description: 'Launch of comprehensive local business directory and mobile app',
            content: 'Introduction of new digital directory and mobile app featuring all local businesses with maps, contact information, reviews, and special offers.',
            image_url: '/images/business-directory.jpg',
            location: 'Excel Centre Technology Center',
            date: '2025-11-15',
            start_time: '17:00',
            end_time: '19:00',
            address: '100 Excel Centre Drive, Digital Innovation Lab',
            category_id: 7
        },
        {
            title: 'Pop-up Shop Program Information Session',
            description: 'Learn about temporary retail space opportunities for new businesses',
            content: 'Information session about pop-up shop program offering temporary retail spaces for emerging businesses to test markets and build customer base.',
            image_url: '/images/popup-shop.jpg',
            location: 'Stratford Retail Development Office',
            date: '2025-11-18',
            start_time: '18:00',
            end_time: '19:30',
            address: 'Stratford Shopping Centre, Retail Services Office',
            category_id: 7
        },
        {
            title: 'Business Security and Fraud Prevention Workshop',
            description: 'Security measures for local business owners',
            content: 'Workshop for business owners covering security systems, fraud prevention, employee training, and creating safe shopping environments for customers.',
            image_url: '/images/business-security.jpg',
            location: 'Excel Centre Security Training Room',
            date: '2025-11-22',
            start_time: '14:00',
            end_time: '16:30',
            address: '100 Excel Centre Drive, Security Education Center',
            category_id: 7
        },
        {
            title: 'Local Food and Restaurant Week',
            description: 'Week-long celebration of local restaurants and food businesses',
            content: 'Special promotion week featuring local restaurants, cafes, and food businesses with special menus, cooking demonstrations, and food tastings.',
            image_url: '/images/restaurant-week.jpg',
            location: 'Multiple Restaurant Locations',
            date: '2025-11-25',
            start_time: '11:00',
            end_time: '21:00',
            address: 'Various Local Restaurant Locations',
            category_id: 7
        },
        {
            title: 'Business Plan Development Workshop',
            description: 'Workshop helping entrepreneurs develop comprehensive business plans',
            content: 'Multi-session workshop guiding participants through business plan development including market analysis, financial projections, and growth strategies.',
            image_url: '/images/business-plan.jpg',
            location: 'Community Center Business Development Room',
            date: '2025-11-29',
            start_time: '18:30',
            end_time: '21:00',
            address: '789 Community Way, Entrepreneurship Development Center',
            category_id: 7
        },
        {
            title: 'Local Service Provider Showcase',
            description: 'Meet local service professionals and learn about their offerings',
            content: 'Showcase featuring local service providers including contractors, consultants, health practitioners, and professional services available in the community.',
            image_url: '/images/service-provider-showcase.jpg',
            location: 'Central Park Professional Services Pavilion',
            date: '2025-12-02',
            start_time: '17:00',
            end_time: '20:00',
            address: 'Central Park, Professional Services Area',
            category_id: 7
        },
        {
            title: 'E-commerce for Local Businesses Workshop',
            description: 'Help local businesses develop online presence and sales',
            content: 'Workshop teaching local business owners how to set up online stores, manage digital marketing, and expand their reach through e-commerce platforms.',
            image_url: '/images/ecommerce-workshop.jpg',
            location: 'Excel Centre Digital Marketing Lab',
            date: '2025-12-06',
            start_time: '13:00',
            end_time: '17:00',
            address: '100 Excel Centre Drive, Digital Business Center',
            category_id: 7
        },
        {
            title: 'Customer Service Excellence Training',
            description: 'Training for local business staff in exceptional customer service',
            content: 'Training program for local business employees covering customer service best practices, conflict resolution, and creating positive shopping experiences.',
            image_url: '/images/customer-service-training.jpg',
            location: 'Stratford Training Center',
            date: '2025-12-09',
            start_time: '09:00',
            end_time: '15:00',
            address: 'Stratford Shopping Centre, Professional Training Facility',
            category_id: 7
        },
        {
            title: 'Local Business Awards and Recognition Ceremony',
            description: 'Annual awards celebrating outstanding local businesses',
            content: 'Awards ceremony recognizing excellent local businesses in various categories including customer service, innovation, community involvement, and business growth.',
            image_url: '/images/business-awards.jpg',
            location: 'Excel Centre Main Banquet Hall',
            date: '2025-12-13',
            start_time: '19:00',
            end_time: '22:00',
            address: '100 Excel Centre Drive, Grand Ballroom',
            category_id: 7
        },
        {
            title: 'New Year Local Business Planning Session',
            description: 'Strategic planning session for local business community',
            content: 'Collaborative planning session for local business owners to discuss community economic development, shared marketing initiatives, and mutual support strategies.',
            image_url: '/images/business-planning.jpg',
            location: 'Community Center Business Conference Room',
            date: '2025-12-16',
            start_time: '18:00',
            end_time: '21:00',
            address: '789 Community Way, Business Strategy Center',
            category_id: 7
        }
    ];

    // Insert sample events
    sampleEvents.forEach(event => {
        try {
            const result = eventQueries.createEvent.run(
                event.title,
                event.description,
                event.content,
                event.image_url,
                event.location,
                event.date,
                event.start_time,
                event.end_time,
                event.address,
                event.category_id
            );
            console.log(`✓ Created event: "${event.title}" (ID: ${result.lastInsertRowid})`);
        } catch (error) {
            console.error(`Error creating event "${event.title}":`, error.message);
        }
    });

    console.log('\n✓ Database seeding completed successfully!');
    console.log(`${sampleEvents.length} events have been added to the database across 7 categories.`);
    console.log('Each category now has 20 comprehensive events with realistic details.');

} catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
}